/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import javax.swing.JLabel;
import javax.swing.JTextPane;

/**
 *
 * @author at289
 */
public class EditorPnl extends javax.swing.JPanel {

   
    public EditorPnl() {
        initComponents();
    }

    public JLabel getLetters() {
        return Letters;
    }

    public JLabel getLines() {
        return Lines;
    }

    public JTextPane getTxtEditor() {
        return TxtEditor;
    }

    public JLabel getWords() {
        return Words;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Lines = new javax.swing.JLabel();
        Letters = new javax.swing.JLabel();
        Words = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtEditor = new javax.swing.JTextPane();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        Lines.setText("Lines");
        jPanel1.add(Lines);

        Letters.setText("Letters");
        jPanel1.add(Letters);

        Words.setText("Words");
        jPanel1.add(Words);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(TxtEditor);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Letters;
    private javax.swing.JLabel Lines;
    private javax.swing.JTextPane TxtEditor;
    private javax.swing.JLabel Words;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
